entrypoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-net

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

api:
  insecure: true
  dashboard: true